name: Push
on:
  push:
    branches:
      - main

jobs:
  update-dist-and-release:
    name: Update dist files and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
          cache: yarn

      - run: yarn install

      - run: yarn build

      - uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          file_pattern: dist/**
          commit_message: 'chore(dist): Update dist [automated commit]'
          commit_user_name: cobraz
          commit_user_email: cobraz@users.noreply.github.com

      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      - if: ${{ steps.release.outputs.release_created }}
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
